name: test

on:
  workflow_call:
    inputs:
      github-repo:
        required: true
        type: string
      goprivate:
        required: true
        type: string
    secrets:
      github-token:
        required: true
jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
