on:
  workflow_call:
    inputs:
      sentry-enabled:
        required: false
        type: boolean
        default: true
    secrets:
      sentry-token:
        required: false
      sentry-org:
        required: false
      releases-slack-webhook-url:
        required: true
      alerts-slack-webhook-url:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .SEMVER file
        id: getversion
        run: echo "::set-output name=version::$(cat .SEMVER)"

      - name: Release the Kraken
        uses: podium-education/kraken@v0.4.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          github-sha: ${{ github.sha }}
          version: ${{ steps.getversion.outputs.version }}
          git-tag-mode: on
          git-tag-format: v<version>

      - name: Create Sentry release
        if: ${{ inputs.sentry-enabled }}
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.sentry-token }}
          SENTRY_ORG: ${{ secrets.sentry-org }}
          SENTRY_PROJECT: ${{ github.event.repository.name }}
        with:
          version: ${{ github.event.repository.name }}@v${{ steps.getversion.outputs.version }}

      - name: Alert Slack of release
        id: slack
        uses: slackapi/slack-github-action@v1.21
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "version": "${{ steps.getversion.outputs.version }}" 
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.releases-slack-webhook-url }}

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}