on:
  workflow_call:
    inputs:
      goprivate:
        required: true
        type: string
      aws-region:
        required: true
        type: string
      aws-account-id:
        required: true
        type: string
      run-docker-tester:
        required: false
        type: boolean
        default: false
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      github-token:
        required: true
      alerts-slack-webhook-url:
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup for private repo Go modules
        env:
          GOPRIVATE: ${{ inputs.goprivate }}
          TOKEN: ${{ secrets.github-token }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
          go mod download
          go mod vendor 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build source:tester
        if: ${{ inputs.run-docker-tester }}
        uses: docker/build-push-action@v3
        with:
          target: source
          context: .
          push: false
          tags: |
            local/source:tester
          build-args: |
            aws_account_id=${{ inputs.aws-account-id }}

      - name: Docker run source:tester
        if: ${{ inputs.run-docker-tester }}
        run: |
          docker run local/source:tester

      - name: Docker build latest
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            local/${{ github.event.repository.name }}:latest
          build-args: |
            aws_account_id=${{ inputs.aws-account-id }}

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}