on:
  workflow_call:
    inputs:
      go-version:
        required: false
        type: string
        default: "1.18.x"
      goprivate:
        required: true
        type: string
      codecov-enabled:
        required: false
        type: boolean
        default: true
    secrets:
      codecov-token:
        required: false
      github-token:
        required: true
      alerts-slack-webhook-url:
        required: true
env:
  CODECOV_TOKEN: ${{ secrets.codecov-token }}

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}

      - name: Setup for private repo Go modules
        env:
          GOPRIVATE: ${{ inputs.goprivate }}
          TOKEN: ${{ secrets.github-token }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
          go mod download

      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: ${{ inputs.codecov-enabled }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Build
        run: make

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}