on:
  workflow_call:
    inputs:
      goprivate:
        required: true
        type: string
      codecov-enabled:
        required: false
        type: boolean
        default: true
    secrets:
      codecov-token:
        required: false
      github-token:
        required: true
      alerts-slack-webhook-url:
        required: true
env:
  CODECOV_TOKEN: ${{ secrets.codecov-token }}

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup for private repo Go modules
        env:
          GOPRIVATE: ${{ inputs.goprivate }}
          TOKEN: ${{ secrets.github-token }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
          go mod download
          go mod vendor 

      - name: Lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build tester image
        uses: docker/build-push-action@v3
        with:
          target: source
          context: .
          push: false
          tags: |
            local:tester

      - name: Docker run go vet
        run: |
          docker run local:tester go vet ./...

      - name: Docker run go test coverage
        run: |
          docker run -v tmp:/src/tmp local:tester go test -race -coverprofile=tmp/coverage.txt -covermode=atomic ./...
          mv tmp/coverage.txt .

      - name: Upload coverage to codecov
        if: ${{ inputs.codecov-enabled }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Docker run make
        run: |
          docker run local:tester make

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}
