on:
  workflow_call:
    inputs:
      goprivate:
        required: true
        type: string
      codecov-enabled:
        required: false
        type: boolean
        default: true
      golangci-lint-enabled:
        required: false
        type: boolean
        default: true
    secrets:
      codecov-token:
        required: false
      github-token:
        required: true
      alerts-slack-webhook-url:
        required: true

jobs:
  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup for private repo Go modules
        env:
          GOPRIVATE: ${{ inputs.goprivate }}
          TOKEN: ${{ secrets.github-token }}
        run: |
          git config --global url."https://${TOKEN}:x-oauth-basic@github.com".insteadOf "https://github.com"
          go mod download
          go mod vendor 

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Lint
        if: ${{ inputs.golangci-lint-enabled }}
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Docker build
        run: |
          docker build --target source -t source:latest .     

      - name: Docker run go vet
        run: |
          docker run source:latest go vet ./...

      - name: Docker run go test coverage
        run: |
          docker run -v ${{ github.workspace }}/tmp:/src/tmp source:latest go test -race -coverprofile=tmp/coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        if: ${{ inputs.codecov-enabled }}
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.codecov-token }}
          files: ./tmp/coverage.txt

      - name: Docker run make
        run: |
          docker run source:latest make

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}
