on:
  workflow_call:
    inputs:
      codecov-enabled:
        required: false
        type: boolean
        default: true
    secrets:
      codecov-token:
        required: false
      github-token:
        required: true
      alerts-slack-webhook-url:
        required: true
env:
  CODECOV_TOKEN: ${{ secrets.codecov-token }}

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup for private repo
        env:
          TOKEN: ${{ secrets.github-token }}
        run: |
          pip install wheel
          sed "s/git+ssh:\/\/git@github.com/git+https:\/\/${TOKEN}:x-oauth-basic@github.com/g"  requirements.txt > requirements_updated.txt
          mv requirements_updated.txt requirements.txt
          pip wheel --wheel-dir=wheels -r requirements.txt
          pip install wheel

      - name: Run coverage
        run: echo "run test with coverage"

      - name: Upload coverage to Codecov
        if: ${{ inputs.codecov-enabled }}
        run: bash <(curl -s https://codecov.io/bash)

      - name: Alert Slack of failure
        uses: slackapi/slack-github-action@v1.21
        if: failure()
        with:
          payload: |
            {
              "github_repository": "${{ github.event.repository.name }}",
              "workflow": "${{ github.workflow }}",
              "action_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", 
              "status": "${{ job.status }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.alerts-slack-webhook-url }}